name: Git Clone, Unzip, Install, and Run

on:
  push:
    branches:
      - main  # Jalankan setiap ada push di branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the target repository
    - name: Clone kayna repository
      run: |
        git clone https://github.com/madz405/kayna.git

    # Step 2: Navigate into the RepositoryName directory
    - name: Change directory to kayna
      run: cd kayna

    # Step 3: Unzip lilybot.zip file inside the RepositoryName folder
    - name: Unzip V18.zip
      run: |
        sudo apt-get install unzip  # Install unzip tool if not already installed
        unzip kayna/V18.zip -d ./kayna # Unzip V18.zip in the RepositoryName directory

    # Step 4: Install npm dependencies
    - name: Install npm dependencies
      run: |
        cd kayna
        npm install 

    # Step 5: Start the npm application
    - name: Start the application
      run: |
        cd kayna
        npm start
